version: '3'
services:
  dev:
    container_name: songs-ui-container
    image: songs-ui-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
